print('Cuadrado original:')
print('* * * * * *')
print('*         *')
print('*         *')
print('*         *')
print('* * * * * *')

print()

print('Cuadrado en una solo linea:')
print('* * * * * *\n*         *\n*         *\n*         *\n* * * * * *')

print()

print('Cuadrado grande:')
print('* * * * * * * * *')
print('*               *')
print('*               *')
print('*               *')
print('*               *')
print('*               *')
print('*               *')
print('* * * * * * * * *')

print()

print('Cuadrado doble:')
print('* * * * * * '*2)
print('*         * '*2)
print('*         * '*2)
print('*         * '*2)
print('* * * * * * '*2)

print(end='\n\n')

print('Flecha original:')
print('  * * * *')
print('  *     *')
print('  *     *')
print('  *     *')
print('* *     * *')
print(' *       *')
print('  *     *')
print('   *   *')
print('    * *')
print('     *')

print()

print('Flecha en una solo linea:')

print('  * * * *\n  *     *\n  *     *\n  *     *\n* *     * *\n *       *\n  *     *\n   *   *\n    * *\n     *')

print()

print('Cuadrado grande:')
print('      * * * * *')
print('      *       *')
print('      *       *')
print('      *       *')
print('      *       *')
print('      *       *')
print('      *       *')
print('* * * *       * * * *')
print(' *                 *')
print('  *               *')
print('   *             *')
print('    *           *')
print('     *         *')
print('      *       *')
print('       *     *')
print('        *   *')
print('         * *')
print('          *')

print()

print('Flecha doble:')
print('  * * * *   '*2)
print('  *     *   '*2)
print('  *     *   '*2)
print('  *     *   '*2)
print('* *     * * '*2)
print(' *       *  '*2)
print('  *     *   '*2)
print('   *   *    '*2)
print('    * *     '*2)
print('     *      '*2)